---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-operator-config
  namespace: kube-system
  labels:
    app: rocketmq-operator
    release: "0.1"
data:
  operator-config.yaml: |
    #namespace: rocketmq-operator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq-operator
  namespace: kube-system
  labels:
    release: "0.1"
    app: rocketmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-operator
  template:
    metadata:
      labels:
        app: rocketmq-operator
    spec:
      serviceAccountName: rocketmq-operator
      volumes:
        - name: rocketmq-operator-config-volume
          configMap:
            name: rocketmq-operator-config
      containers:
      - name: rocketmq-operator-controller
        imagePullPolicy: IfNotPresent
        image: huanwei/rocketmq-operator:0.1
        ports:
        - containerPort: 10254
        volumeMounts:
        - name: rocketmq-operator-config-volume
          mountPath: /etc/rocketmq-operator
        args:
          - --v=4
          - --namespace=kube-system
