---
apiVersion: "rocketmq.huanwei.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: mybrokercluster
  namespace : default
spec:
  brokerImage: huanwei/rocketmq-broker:4.3.0-operator
  nameServers: 10.254.34.35:9876;10.254.34.63:9876
  allMaster: false
  replicationMode: SYNC
  groupReplica: 2
  membersPerGroup: 2
