---
apiVersion: "rocketmq.rivernet.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: mybrokercluster
  namespace : default
spec:
  brokerImage: rivernet/rocketmq-broker:4.3.0-operator
  allMaster: true
  replicationMode: SYNC
  nameSrvReplica: 2
  groupReplica: 2
  membersPerGroup: 2
