---
apiVersion: "rocketmq.rivernet.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: zwtest
  namespace : default
spec:
  brokerImage: rivernet/rocketmq-broker:4.3.0-operator
  nameSvrImage: rivernet/rocketmq-namesrv:4.3.0-k8s
  nameSrvReplica: 2
  allMaster: false
  replicationMode: SYNC
  groupReplica: 2
  membersPerGroup: 2
  nameSvrStorage:
    dataDiskSize: 2Gi
    fastMode: true
  brokerStorage:
    dataDiskSize: 1Gi
    fastMode: true
    
    
