apiVersion: "rocketmq.rivernet.io/v1alpha1"
kind: BrokerCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  brokerImage: rivernet/rocketmq-broker:4.3.0-operator
  nameSvrImage: rivernet/rocketmq-namesrv:4.3.0-k8s
  nameSrvReplica: {{ .Values.replicas.variables.nameSrvReplica.value }}
  allMaster: false
  replicationMode: SYNC
  groupReplica:  {{ .Values.replicas.variables.groupReplica.value }}
  membersPerGroup: {{ .Values.replicas.variables.membersPerGroup.value }}
{{- if .Values.nameSvrPersistence.enabled }}
  nameSvrStorage:
    dataDiskSize: {{ .Values.nameSvrPersistence.variables.size.value }}Gi
    storageClass: {{ .Values.nameSvrPersistence.variables.storagePool.value }}
  {{- if (eq "Fast" .Values.nameSvrPersistence.variables.type.value ) }}
    fastMode: true
  {{- end }}
{{- end }}
{{- if .Values.brokerPersistence.enabled }}
  brokerStorage:
    dataDiskSize: {{ .Values.brokerPersistence.variables.size.value }}Gi
    storageClass: {{ .Values.brokerPersistence.variables.storagePool.value }}
  {{- if (eq "Fast" .Values.brokerPersistence.variables.type.value ) }}
    fastMode: true
  {{- end }}
{{- end }}
